In [15]:
os.getcwd()

'c:\\Users\\KANAK LARHARE\\Documents\\Spotify-Music-Analytics\\notebooks'

In [16]:
os.listdir()

['data_cleaning.ipynb', 'load_to_postgres.ipynb']

In [17]:

os.listdir('../data')

['spotify_cleaned.csv', 'spotify_final.csv', 'spotify_raw.csv']

In [18]:
import pandas as pd

df = pd.read_csv('../data/spotify_final.csv')

df.head()

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,...,liveness,valence,tempo,time_signature,track_genre,duration_min,energy_level,popularity_category,tempo_category,danceability_category
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,1,...,0.3580,0.715,87.917,4,acoustic,3.844433,Medium,Popular,Slow,Medium
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,1,...,0.1010,0.267,77.489,4,acoustic,2.493500,Low,Popular,Slow,Medium
2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,0,...,0.1170,0.120,76.332,4,acoustic,3.513767,Medium,Popular,Slow,Medium
3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,0,...,0.1320,0.143,181.740,3,acoustic,3.365550,Low,Popular,Fast,Low
4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,2,...,0.0829,0.167,119.949,4,acoustic,3.314217,Medium,Hit,Medium,Medium

In [20]:
from sqlalchemy import create_engine

engine = create_engine(
    'postgresql+psycopg2://postgres:@Kanak20@localhost:5432/spotify_db'
)

df.to_sql(
    'spotify_tracks',
    engine,
    if_exists='replace',
    index=False
)

print("Data loaded successfully!")

OperationalError: (psycopg2.OperationalError) could not translate host name "Kanak20@localhost" to address: Non-recoverable failure in name resolution

(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [22]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

password = quote_plus("@Kanak")  # replace with your actual password

engine = create_engine(
    f'postgresql+psycopg2://postgres:{password}@localhost:5432/spotify_db'
)

In [25]:
with engine.connect() as conn:
    print("Connected successfully!")

OperationalError: (psycopg2.OperationalError) could not translate host name "Kanak@localhost" to address: Non-recoverable failure in name resolution

(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [26]:
import pandas as pd
from sqlalchemy import create_engine
from urllib.parse import quote_plus

# Read dataset
df = pd.read_csv(r'C:\Users\KANAK LARHARE\Documents\Spotify-Music-Analytics\data\spotify_final.csv')

# Encode password
password = quote_plus('@Kanak')   # Replace with your actual password

# Create connection
engine = create_engine(
    f'postgresql+psycopg2://postgres:{password}@localhost:5432/spotify_db'
)

# Test connection
with engine.connect() as conn:
    print("Connected successfully!")

# Load data
df.to_sql(
    'spotify_tracks',
    engine,
    if_exists='replace',
    index=False
)

print("Data loaded successfully!")

OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "postgres"

(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [27]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

password = quote_plus("@Kanak20")

engine = create_engine(
    f"postgresql+psycopg2://postgres:{password}@localhost:5432/postgres"
)

with engine.connect() as conn:
    print("Connected successfully!")

Connected successfully!

In [28]:
import pandas as pd

df = pd.read_csv(
    r'C:\Users\KANAK LARHARE\Documents\Spotify-Music-Analytics\data\spotify_final.csv'
)

df.head()

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,...,liveness,valence,tempo,time_signature,track_genre,duration_min,energy_level,popularity_category,tempo_category,danceability_category
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,1,...,0.3580,0.715,87.917,4,acoustic,3.844433,Medium,Popular,Slow,Medium
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,1,...,0.1010,0.267,77.489,4,acoustic,2.493500,Low,Popular,Slow,Medium
2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,0,...,0.1170,0.120,76.332,4,acoustic,3.513767,Medium,Popular,Slow,Medium
3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,0,...,0.1320,0.143,181.740,3,acoustic,3.365550,Low,Popular,Fast,Low
4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,2,...,0.0829,0.167,119.949,4,acoustic,3.314217,Medium,Hit,Medium,Medium

In [29]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

password = quote_plus("@Kanak20")

engine = create_engine(
    f"postgresql+psycopg2://postgres:{password}@localhost:5432/spotify_db"
)

In [ ]:
df.to_sql(
    "spotify_tracks",
    engine,
    if_exists="replace",
    index=False
)

print("Data loaded successfully!")

Data loaded successfully!

: